___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
my_list = [5, 10, 15, 20, 25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [4]:
# YOUR CODE IS HERE

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [7]:
# YOUR CODE IS HERE
np.ones((4,4), dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [8]:
# YOUR CODE IS HERE

np.ones((4,4), dtype="int") * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [9]:
# YOUR CODE IS HERE

np.full((4,4), 7, dtype="int")


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [10]:
# YOUR CODE IS HERE

np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [12]:
# YOUR CODE IS HERE

np.arange(25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [17]:
# YOUR CODE IS HERE

# np.linspace(0, 24, 25, dtype="int").reshape(5,5)
np.linspace(0, 25, 25, dtype="int", endpoint=False).reshape(5,5) # endpoint=False ----> stop inclusive

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [18]:
# YOUR CODE IS HERE

np.random.rand(5)

array([0.21517004, 0.26392623, 0.14577289, 0.07612985, 0.18808699])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [19]:
# YOUR CODE IS HERE

np.random.rand(5,5)

array([[0.08884243, 0.77431515, 0.17624452, 0.71372822, 0.86745399],
       [0.77234222, 0.34950708, 0.86823677, 0.15997176, 0.62267189],
       [0.64262133, 0.45597943, 0.26998334, 0.0982779 , 0.18753041],
       [0.34871868, 0.14191657, 0.45637584, 0.04832888, 0.82021627],
       [0.47004195, 0.76011173, 0.41120717, 0.19131336, 0.72540648]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [20]:
# YOUR CODE IS HERE

np.random.randint(20, 50, size=(3,4))

array([[24, 32, 29, 47],
       [22, 48, 28, 48],
       [42, 28, 41, 32]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [21]:
# YOUR CODE IS HERE

ranarr = np.random.randint(0, 100, 48)
ranarr

array([26, 98, 57, 46, 59, 63, 29, 86, 21,  7, 21, 23, 28,  4, 52, 86, 36,
       40, 10, 77, 67, 19, 98, 37,  6, 87,  3, 64, 28,  5, 86, 16, 44, 67,
       56, 74, 22, 23, 25, 79, 15, 78, 55, 38, 81, 51, 26, 78])

In [22]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6,8)

array([[26, 98, 57, 46, 59, 63, 29, 86],
       [21,  7, 21, 23, 28,  4, 52, 86],
       [36, 40, 10, 77, 67, 19, 98, 37],
       [ 6, 87,  3, 64, 28,  5, 86, 16],
       [44, 67, 56, 74, 22, 23, 25, 79],
       [15, 78, 55, 38, 81, 51, 26, 78]])

In [23]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(-1, 8)

array([[26, 98, 57, 46, 59, 63, 29, 86],
       [21,  7, 21, 23, 28,  4, 52, 86],
       [36, 40, 10, 77, 67, 19, 98, 37],
       [ 6, 87,  3, 64, 28,  5, 86, 16],
       [44, 67, 56, 74, 22, 23, 25, 79],
       [15, 78, 55, 38, 81, 51, 26, 78]])

In [24]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6, -1)

array([[26, 98, 57, 46, 59, 63, 29, 86],
       [21,  7, 21, 23, 28,  4, 52, 86],
       [36, 40, 10, 77, 67, 19, 98, 37],
       [ 6, 87,  3, 64, 28,  5, 86, 16],
       [44, 67, 56, 74, 22, 23, 25, 79],
       [15, 78, 55, 38, 81, 51, 26, 78]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [25]:
# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [26]:
# YOUR CODE IS HERE 
mat[1:3,1:3] # mat[1 : 3, [1, 2]] (slicing + fancy indexing)

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [27]:
# YOUR CODE IS HERE 
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [29]:
# YOUR CODE IS HERE 
mat[1,::2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [30]:
# YOUR CODE IS HERE 
mat[:, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [31]:
# YOUR CODE IS HERE 
mat[[1, 3],[0, 2]] # [(rows), (columns)]

# x = mat[1,0]
# y = mat[3,2]
# mat6 = np.hstack([x,y])    # w/ hstack method

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [32]:
# YOUR CODE IS HERE 
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [33]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [34]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [35]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [36]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [37]:
# YOUR CODE IS HERE 

(mat[mat<10] + mat[mat>12]).std()

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [38]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [41]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat[:, 2]= [3, 7, 11, 15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
# YOUR CODE IS HERE 

mat[:, 1].sum()
#np.sum(mat[:, 1])

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [45]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

mat[:,2:3]

array([[ 3],
       [ 7],
       [11],
       [15]])

In [48]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

mat[2]

array([ 9, 10, 11, 12])

In [49]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

np.median(mat[:,2:3]), np.median(mat[2])

(9.0, 10.5)

In [50]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

print(np.mean(mat[:,2:3]))
print(np.mean(mat[2]))

9.0
10.5


In [51]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

print(np.std(mat[:,2:3]))
print(np.std(mat[2]))

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [52]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [56]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 

sal = pd.read_csv("Salaries.csv")

In [57]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 

sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [58]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

sal.sample()

Id   EmployeeName                   JobTitle   BasePay  OvertimePay  \
90615  90616  Lawrence  Mah  Automotive Service Worker  64193.65      1023.55   

       OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
90615  11871.71   28679.4  77088.91         105768.31  2013    NaN   

              Agency  Status  
90615  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [59]:
# YOUR CODE IS HERE 

sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [60]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 

sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [61]:
sal.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [62]:
# YOUR CODE IS HERE 

sal["Year"].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [63]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

sal.Year.nunique()

4

In [64]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

sal.Year.unique()

array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [65]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 

sal["TotalPay"].max()

567595.43

In [66]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 

sal["TotalPay"].mean()

74768.321971703

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [67]:
# YOUR CODE IS HERE 

len(sal[sal["TotalPay"] > sal["TotalPay"].mean()])

69489

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [68]:
# YOUR CODE IS HERE 

len(sal[sal["TotalPay"] > sal["TotalPay"].mean()])

69489

### How much does ALBERT PARDINI make money (including benefits)?

In [71]:
# YOUR CODE IS HERE 

sal[sal["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [73]:
# YOUR CODE IS HERE 
sal[sal["TotalPayBenefits"] == sal["TotalPayBenefits"].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [75]:
# YOUR CODE IS HERE 

sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [76]:
# YOUR CODE IS HERE 

sal["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [77]:
# YOUR CODE IS HERE 

sal[(sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()) & (sal["Year"] == 2012)]["EmployeeName"].count()

# sal.loc[ (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean()) & (sal['Year']==2012) ].shape[0]

# sal.loc[ (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean()) & (sal['Year']==2012) ]['EmployeeName'].size

20366

### How many people have a title of Manager in their jobs?

In [79]:
sal.head(2)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN

In [83]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 

len(sal[sal["JobTitle"].apply(lambda x: True if "manager" in x.lower() else False)])

4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [84]:
sal.head(2)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN

In [85]:
# YOUR CODE IS HERE 

sal_new = sal.iloc[:,[0,1,2,7,8]]

sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [88]:
# YOUR CODE IS HERE 

sal_new = sal_new.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [89]:
# YOUR CODE IS HERE 

sal[(sal["TotalPayBenefits"] > sal["TotalPayBenefits"].min()) & (sal["TotalPayBenefits"] < sal["TotalPayBenefits"].mean())]\
[["EmployeeName", "TotalPayBenefits"]]

EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________